# Generated by Django 4.1.5 on 2023-01-26 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ord_no',
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='주문명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='shinhan_comment',
        ),
    ]
